### PR TITLE
Added basic Makefile wrapping rebar. (erlang.fake).

### PR DESCRIPTION
**Pull request by berset**
This helps erlang.mk compat.

### CODE REVIEW

**Comment by sdepold** [comment]
Thanks :) Will check why the tests are failing :-/

**Comment by Minoru** [comment]
For what it's worth, I've observed the same errors when the repo I tried to test on (my own fork of `octo.erl-test`) didn't exist (my bad). But as far as I can see, it's not the case here.

**Comment by sdepold** [comment]
Right. Totally forgot about this PR :(

**Comment by Minoru** [comment]
sdepold, do you have any insight? I used to test on my own fork, and it worked fine. But now I'm trying to test on yours, and [some tests fail the same way they did on Travis](https://gist.github.com/Minoru/3c100c7e9b18339c3381).

**Comment by Minoru** [comment]
Okay, so I asked another person to fork my `octo.erl-test` (yours is a bit broken — `*-clone` branches shouldn't be there) and then run the test on their repo. As expected, I got 5 failures, all in `create*` functions, with error messages looking the same as on Travis and in my log (which isn't much of an evidence since we don't see the error message in its whole, but still). So it seems like Travis fails because it can't get access to the `octo.erl-test` repo.

How can this be? Well, I'm looking on the log on the Travis and I don't see `AUTH_TOKEN` being exported anywhere. @sdepold , I think that's the problem. Can you please generate a key and add it to environment variables for the build? Don't worry, Travis won't show it in the log (it will look like [this](https://travis-ci.org/codingteam/octo.erl#L81)).

**Comment by pxlpnk** [comment]
This could maybe help, taken from the travis documentation:
> [...] we do not provide these values to untrusted builds, triggered by pull requests from another repository.

http://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables

**Comment by sdepold** [comment]
I merged this because it works. Guess I will have to mock the test requests :(

**Pull request merged**
